### ISSUE TITLE
Store similar URLs as one entry in the DB

### ISSUE THREAD

**Issue by a-ys** [SirajChokshi/shorten#2]
* https://google.com should be the same as https://www.google.com
* capitalized urls should be the same

**Comment by SirajChokshi** [comment]
The first one should not be done as a naked URL is NOT equivalent to the `www.` subdomain. While it is good practice to do so, it is not a rule all websites follow.

The latter may work for domain names, but some query strings rely on case sensitive input (e.g. `/?p=string` may not be equivalent to `/?p=STRING`). Be careful when making lowercase comparisons.

**Comment by a-ys** [comment]
Closing this issue. Not worth searching the database each time a URL is created.
