### ISSUE TITLE
Should duplicate entries return the same shortened link?

### ISSUE THREAD

**Issue by a-ys** [SirajChokshi/shorten#4]

**Comment by SirajChokshi** [comment]
I think as long as the link alias is NOT custom (since we're storing that boolean in the database) then it can be returned and used.

**Comment by a-ys** [comment]
Feature added in commit ecbfb5ac7f14ceae04b283c0aa9de321dd480df4. When generating new URLs, if a custom code has already been generated for a given URL (must match exactly with database URL), the previously generated code will be returned.
